"""empty message

Revision ID: 4e01e666c7af
Revises: 
Create Date: 2021-12-03 11:48:57.856769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e01e666c7af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_state')
    op.alter_column('guest', 'profilepix',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(None, 'lga', 'state', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lga', type_='foreignkey')
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('guest', 'profilepix',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.create_table('tbl_state',
    sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('state_name', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('state_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
